apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
spec:
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: bastion
        image: busybox:latest
        command: ["sleep", "3600"]
