apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
spec:
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      volumes:
      - name: awscli
        emptyDir: {}
      containers:
      - name: awscli
        image: amazon/aws-cli:latest
        command: ["sleep", "3600"]
        volumeMounts:
        - name: awscli
          mountPath: /data
