apiVersion: apps/v1
kind: Deployment
metadata:
  name: john2143-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: john2143-com
  template:
    metadata:
      labels:
        app: john2143-com
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: files-pvc

      containers:
      - name: john2143-com
        image: ghcr.io/john2143/john2143.com:23
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/juushFiles
          name: data-volume

---
apiVersion: v1
kind: Service
metadata:
  name: john2143-com
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: john2143-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: mongodata
        #emptyDir:
          #sizeLimit: 50Mi
        persistentVolumeClaim:
          claimName: mongo-pvc

      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass

        volumeMounts:
          - mountPath: /data/db
            name: mongodata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage-retain
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: http
  selector:
    app: mongo
