apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coffee
spec:
  parentRefs:
  - name: cafe
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /coffee
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
      # name of the service
    - name: coffee
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tea
spec:
  parentRefs:
  - name: cafe
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /tea
    backendRefs:
      # name of the service
    - name: tea
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: access-to-coffee
  namespace: nginx-gateway # where the gateway lives
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: default # where the target pods live
  to:
  - group: ""
    kind: Service 
