apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coffee
spec:
  parentRefs:
  - name: cafe
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /aaa/
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
    backendRefs:
      # name of the service
    - name: coffee
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /bbb/
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /b/
    backendRefs:
      # name of the service
    - name: coffee
      port: 80
