apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cafe
  #annotations:
    #cert-manager.io/issuer: letsencrypt-prod
spec:
  listeners:
  # certs are renewed via http challenge
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same

  - name: poe-sale
    hostname: poe.sale
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: poe-sale-tls-key-prod
        namespace: default

  - name: https-gay
    hostname: "2143.gay"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-gay-tls-key-prod
        namespace: default
  - name: https-gay-all
    hostname: "*.2143.gay"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-gay-tls-key-prod
        namespace: default


  - name: https-christmas
    hostname: 2143.christmas
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-christmas-tls-key-prod
        namespace: default
  - name: https-christmas-all
    hostname: "*.2143.christmas"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-christmas-tls-key-prod
        namespace: default


  - name: https-baby
    hostname: 2143.baby
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-baby-tls-key-prod
        namespace: default
  - name: https-baby-all
    hostname: "*.2143.baby"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-baby-tls-key-prod
        namespace: default

  - name: 2143.me
    hostname: 2143.me
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-me-tls-key-prod2
        namespace: default
  - name: 2143.me-all
    hostname: "*.2143.me"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-me-tls-key-prod2
        namespace: default

  - name: 2143.moe
    hostname: 2143.moe
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-moe-tls-key-prod
        namespace: default
  - name: 2143.moe-all
    hostname: "*.2143.moe"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-moe-tls-key-prod
        namespace: default

  - name: brick-gay
    hostname: brick.gay
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: brick-gay-tls-key-prod
        namespace: default
  - name: brick-gay-all
    hostname: "*.brick.gay"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: brick-gay-tls-key-prod
        namespace: default

  - name: ewan-all
    hostname: "*.ewan.green"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: ewan-green-tls-key-prod
        namespace: default
