apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cafe
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  listeners:
  # certs are renewed via http challenge
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same

  - name: https-gay
    hostname: 2143.gay
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-gay-tls-key-prod
        namespace: default

  - name: https-christmas
    hostname: 2143.christmas
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-christmas-tls-key-prod
        namespace: default

  - name: https-christmas-misskey
    hostname: misskey.2143.christmas
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-christmas-tls-key-prod
        namespace: default

  - name: https-baby
    hostname: 2143.baby
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: 2143-baby-key-prod
        namespace: default
