apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/kubernetes/kube-state-metrics/examples/standard
- cluster-issuer.yaml
- certs.yaml
- pvc.yaml
- https-redirect.yaml
#- misskey.yaml
secretGenerator:
- name: s3cmd-minio
  files:
  - ./s3cmd.txt
patches:
- path: gateway.yaml
- path: loadbalancer.yaml
- path: deployment.yaml
#- path: httproute.yaml
# also remove the env var "S3_ENDPOINT_URL"
#- target:
    #kind: Deployment
    #name: john2143-com
  #patch: |
    #- op: remove
      #path: /spec/template/spec/containers/0/env/0
images:
- name: imagehost:latest
  newName: ghcr.io/john2143/john2143.com
  newTag: "79"
