apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/kubernetes/kube-state-metrics/examples/standard
- cluster-issuer.yaml
- certs.yaml
- pvc.yaml
- https-redirect.yaml
- deployment-redirector.yaml
- grafana-routes.yaml
- horizontalpodautoscaler.yaml
#- misskey.yaml
#- path: loadbalancer.yaml
patches:
- path: gateway.yaml
- path: deployment.yaml
- path: httproute.yaml
- path: deployment-bastion.yaml
  target:
    kind: Deployment
    name: john2143-com
#- path: httproute.yaml
# also remove the env var "S3_ENDPOINT_URL"
#- target:
    #kind: Deployment
    #name: john2143-com
  #patch: |
    #- op: remove
      #path: /spec/template/spec/containers/0/env/0


images:
- name: bot:latest
  newName: ghcr.io/2143-labs/openfront-api-discordbot
  newTag: openfront-api-discordbot-latest
- name: imagehost:latest
  newName: ghcr.io/john2143/john2143.com
  newTag: "135"
- name: openfrontpro-sim:latest
  newName: ghcr.io/2143-labs/openfrontpro-sim
  newTag: openfrontpro-latest
- name: openfrontpro:latest
  newName: ghcr.io/2143-labs/openfrontpro-rs
  newTag: openfrontpro-latest
