apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gotk-components.yaml
  - gitrepository.yaml
  - kustomization-prod.yaml
  - notification-provider.yaml
  - notification-alert.yaml
