apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/2143-Labs/2143-k8s
  secretRef:
    name: github-token
  commitStatusExpr: "'Flux/prod'"
