apiVersion: apps/v1
kind: Deployment
metadata:
  name: john2143-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: john2143-com
  template:
    metadata:
      labels:
        app: john2143-com
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: files-pvc

      containers:
      - name: john2143-com
        image: imagehost:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/juushFiles
          name: data-volume
        env:
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: S3_ENDPOINT_URL
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-creds
              key: S3_SECRET_KEY
        - name: BUCKET
          value: imagehost-files
        - name: FOLDER
          value: public-prod
        - name: DB
          value: mongodb://admin:pass@mongo
        - name: PORT
          value: "3000"
        - name: IP
          value: "0.0.0.0"
        - name: NODE_ENV
          value: production
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: john2143-com
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: john2143-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: mongodata
        #emptyDir:
          #sizeLimit: 50Mi
        persistentVolumeClaim:
          claimName: mongo-pvc

      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pass

        volumeMounts:
          - mountPath: /data/db
            name: mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: http
  selector:
    app: mongo
