apiVersion: v1
kind: Service
metadata:
  name: home-endpoint
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: ExternalName
  externalName: john2143.com
