apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: john2143-com-normal
spec:
  parentRefs:
  - name: cafe
  hostnames:
  - "2143.christmas"
  - "2143.baby"
  - "2143.gay"
  - "2143.me"
  - "2143.moe"
  - "prod.john2143.com"
  - "brick.gay"
  - "9s.pics"
  - "0x2b.pics"
  - "localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      # name of the service
    - name: john2143-com
      port: 80
      namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: john2143-com-i-prefix
spec:
  parentRefs:
  - name: cafe
  hostnames:
  - "i.2143.christmas"
  - "i.2143.baby"
  - "i.2143.gay"
  - "i.2143.me"
  - "i.2143.moe"
  - "i.prod.john2143.com"
  - "i.brick.gay"
  - "i.9s.pics"
  - "i.0x2b.pics"
  - "m.ewan.green"
  rules:

  - matches:
    - path:
        type: PathPrefix
        value: /uf
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /uf
    backendRefs:
      # name of the service
    - name: john2143-com
      port: 80
      namespace: default

  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /f/
    backendRefs:
      # name of the service
    - name: john2143-com
      port: 80
      namespace: default

  - matches:
    - path:
        type: PathPrefix
        value: /f/
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /f/
    backendRefs:
      # name of the service
    - name: john2143-com
      port: 80
      namespace: default
