apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployments.yaml
- gateway.yaml
- httproute.yaml
- nginx-fabric.yaml
- endpoint-base.yaml
- client-settings-policy.yaml
# Add the crds for gateway api
- github.com/nginxinc/nginx-gateway-fabric/config/crd/gateway-api/standard

