name: Build and push derper

on:
  push:
    paths:
      - Dockerfile.derper
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, nixos]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build -f Dockerfile.derper -t ghcr.io/2143-labs/derper:latest .
          docker push ghcr.io/2143-labs/derper:latest
